# frozen_string_literal: true

# Demo seed: realistic data for portfolio demos, walkthroughs, and internal validation.
# Safe to run in development. Use rake demo:reset or demo:seed (see lib/tasks/demo.rake).
#
# Provides:
# - Primary demo merchant (demo@example.com) with rich payment history across time
# - Secondary merchant (scoping@example.com) for multi-tenant / policy demos
# - Payment intents in: created, authorized, captured, refunded, failed, canceled
# - Transactions, ledger entries, webhook events with mixed delivery states
# - Timeline spread so "last 7 days", "yesterday", "this week" work in reporting/AI
module Seeds
  module Demo
    DEMO_EMAIL     = 'demo@example.com'
    DEMO_PASSWORD  = 'demo1234'
    SCOPING_EMAIL  = 'scoping@example.com'
    SCOPING_PASSWORD = 'scoping1234'

    class << self
      def run(api_keys: {})
        @api_keys = api_keys
        destroy_demo_merchants
        create_demo_merchant
        create_scoping_merchant
        seed_demo_merchant_data
        seed_scoping_merchant_data
        build_summary
      end

      def summary
        @summary || {}
      end

      private

      def destroy_demo_merchants
        [DEMO_EMAIL, SCOPING_EMAIL].each do |email|
          m = Merchant.find_by(email: email)
          next unless m

          # LedgerEntry, Transaction, etc. destroyed via merchant → payment_intents → transactions
          m.destroy!
        end
      end

      def create_demo_merchant
        @demo_merchant, key = Merchant.create_with_api_key(
          name: 'Demo Store Inc',
          status: 'active',
          email: DEMO_EMAIL,
          password: DEMO_PASSWORD,
          password_confirmation: DEMO_PASSWORD
        )
        @api_keys[DEMO_EMAIL] = key
      end

      def create_scoping_merchant
        @scoping_merchant, key = Merchant.create_with_api_key(
          name: 'Scoping Test Ltd',
          status: 'active',
          email: SCOPING_EMAIL,
          password: SCOPING_PASSWORD,
          password_confirmation: SCOPING_PASSWORD
        )
        @api_keys[SCOPING_EMAIL] = key
      end

      def seed_demo_merchant_data
        m = @demo_merchant
        base_time = Time.current

        # Customers
        c1 = Customer.create!(merchant: m, email: 'alice@demo.example.com', name: 'Alice Chen')
        c2 = Customer.create!(merchant: m, email: 'bob@demo.example.com', name: 'Bob Martinez')
        c3 = Customer.create!(merchant: m, email: 'carol@demo.example.com', name: 'Carol Kim')

        # Payment methods (tokens are generated by model)
        pm1 = PaymentMethod.create!(customer: c1, method_type: 'card', last4: '4242', brand: 'Visa', exp_month: 12, exp_year: 2027)
        pm2 = PaymentMethod.create!(customer: c2, method_type: 'card', last4: '5555', brand: 'Mastercard', exp_month: 6, exp_year: 2026)
        pm3 = PaymentMethod.create!(customer: c3, method_type: 'card', last4: '8888', brand: 'Visa', exp_month: 9, exp_year: 2026)

        # ---- Timeline: 7 days ago to today ----
        # PI: created (no auth yet) - 7 days ago
        pi_created = PaymentIntent.create!(
          merchant: m, customer: c1, payment_method: pm1,
          amount_cents: 2999, currency: 'USD', status: 'created',
          idempotency_key: 'demo_created_001',
          created_at: base_time - 7.days, updated_at: base_time - 7.days
        )

        # PI: authorized (requires_capture) - 5 days ago
        pi_auth = PaymentIntent.create!(
          merchant: m, customer: c1, payment_method: pm1,
          amount_cents: 4999, currency: 'USD', status: 'authorized',
          idempotency_key: 'demo_auth_001',
          created_at: base_time - 5.days, updated_at: base_time - 5.days
        )
        t_auth = Transaction.create!(
          payment_intent: pi_auth, kind: 'authorize', status: 'succeeded',
          amount_cents: 4999, processor_ref: 'demo_txn_auth_001',
          created_at: base_time - 5.days, updated_at: base_time - 5.days
        )

        # PI: captured - 4 days ago (ledger charge)
        pi_captured = PaymentIntent.create!(
          merchant: m, customer: c2, payment_method: pm2,
          amount_cents: 15_000, currency: 'USD', status: 'captured',
          idempotency_key: 'demo_captured_001',
          created_at: base_time - 4.days, updated_at: base_time - 4.days
        )
        t_cap_a = Transaction.create!(
          payment_intent: pi_captured, kind: 'authorize', status: 'succeeded',
          amount_cents: 15_000, processor_ref: 'demo_txn_cap_a',
          created_at: base_time - 4.days, updated_at: base_time - 4.days
        )
        t_cap_b = Transaction.create!(
          payment_intent: pi_captured, kind: 'capture', status: 'succeeded',
          amount_cents: 15_000, processor_ref: 'demo_txn_cap_b',
          created_at: base_time - 4.days, updated_at: base_time - 4.days
        )
        LedgerEntry.create!(
          merchant: m, payment_transaction: t_cap_b, entry_type: 'charge',
          amount_cents: 15_000, currency: 'USD',
          created_at: base_time - 4.days, updated_at: base_time - 4.days
        )

        # PI: captured then partially refunded - 3 days ago
        pi_refunded = PaymentIntent.create!(
          merchant: m, customer: c2, payment_method: pm2,
          amount_cents: 10_000, currency: 'USD', status: 'captured',
          idempotency_key: 'demo_refund_001',
          created_at: base_time - 3.days, updated_at: base_time - 3.days
        )
        Transaction.create!(payment_intent: pi_refunded, kind: 'authorize', status: 'succeeded', amount_cents: 10_000, processor_ref: 'demo_txn_r_a', created_at: base_time - 3.days, updated_at: base_time - 3.days)
        t_cap_r = Transaction.create!(payment_intent: pi_refunded, kind: 'capture', status: 'succeeded', amount_cents: 10_000, processor_ref: 'demo_txn_r_cap', created_at: base_time - 3.days, updated_at: base_time - 3.days)
        LedgerEntry.create!(merchant: m, payment_transaction: t_cap_r, entry_type: 'charge', amount_cents: 10_000, currency: 'USD', created_at: base_time - 3.days, updated_at: base_time - 3.days)
        t_ref = Transaction.create!(payment_intent: pi_refunded, kind: 'refund', status: 'succeeded', amount_cents: 3500, processor_ref: 'demo_txn_ref', created_at: base_time - 3.days + 2.hours, updated_at: base_time - 3.days + 2.hours)
        LedgerEntry.create!(merchant: m, payment_transaction: t_ref, entry_type: 'refund', amount_cents: -3500, currency: 'USD', created_at: base_time - 3.days + 2.hours, updated_at: base_time - 3.days + 2.hours)

        # PI: failed (auth failed) - 2 days ago
        pi_failed = PaymentIntent.create!(
          merchant: m, customer: c3, payment_method: pm3,
          amount_cents: 7999, currency: 'USD', status: 'failed',
          idempotency_key: 'demo_failed_001',
          created_at: base_time - 2.days, updated_at: base_time - 2.days
        )
        Transaction.create!(
          payment_intent: pi_failed, kind: 'authorize', status: 'failed',
          amount_cents: 7999, processor_ref: nil, failure_code: 'card_declined', failure_message: 'Insufficient funds',
          created_at: base_time - 2.days, updated_at: base_time - 2.days
        )

        # PI: canceled - yesterday
        pi_canceled = PaymentIntent.create!(
          merchant: m, customer: c1, payment_method: pm1,
          amount_cents: 1200, currency: 'USD', status: 'canceled',
          idempotency_key: 'demo_cancel_001',
          created_at: base_time - 1.day, updated_at: base_time - 1.day
        )
        Transaction.create!(payment_intent: pi_canceled, kind: 'void', status: 'succeeded', amount_cents: 1200, processor_ref: 'demo_txn_void', created_at: base_time - 1.day, updated_at: base_time - 1.day)

        # Another capture today for "today" / "last 7 days" reporting
        pi_today = PaymentIntent.create!(
          merchant: m, customer: c3, payment_method: pm3,
          amount_cents: 5500, currency: 'USD', status: 'captured',
          idempotency_key: 'demo_today_001',
          created_at: base_time - 2.hours, updated_at: base_time - 2.hours
        )
        Transaction.create!(payment_intent: pi_today, kind: 'authorize', status: 'succeeded', amount_cents: 5500, processor_ref: 'demo_txn_t_a', created_at: base_time - 2.hours, updated_at: base_time - 2.hours)
        t_today = Transaction.create!(payment_intent: pi_today, kind: 'capture', status: 'succeeded', amount_cents: 5500, processor_ref: 'demo_txn_t_cap', created_at: base_time - 2.hours, updated_at: base_time - 2.hours)
        LedgerEntry.create!(merchant: m, payment_transaction: t_today, entry_type: 'charge', amount_cents: 5500, currency: 'USD', created_at: base_time - 2.hours, updated_at: base_time - 2.hours)

        # Webhook events: mix of pending, succeeded, failed (create with final status so delivery job no-ops)
        we_succ = WebhookEvent.create!(
          merchant: m, event_type: 'payment_intent.captured',
          payload: { payment_intent_id: pi_captured.id, amount_cents: 15_000 },
          delivery_status: 'succeeded', delivered_at: base_time - 4.days + 5.minutes, attempts: 1,
          created_at: base_time - 4.days, updated_at: base_time - 4.days
        )

        we_fail = WebhookEvent.create!(
          merchant: m, event_type: 'payment_intent.captured',
          payload: { payment_intent_id: pi_refunded.id, amount_cents: 10_000 },
          delivery_status: 'failed', attempts: 3,
          created_at: base_time - 3.days, updated_at: base_time - 3.days
        )

        we_pend = WebhookEvent.create!(
          merchant: m, event_type: 'payment_intent.authorized',
          payload: { payment_intent_id: pi_auth.id, amount_cents: 4999 },
          delivery_status: 'pending', attempts: 0,
          created_at: base_time - 1.hour, updated_at: base_time - 1.hour
        )

        # AI audit records for replay/analytics demos
        AiRequestAudit.create!(
          request_id: 'demo_req_001', endpoint: '/api/v1/ai/chat', merchant_id: m.id,
          agent_key: 'payment_support', success: true, tool_used: true, tool_names: ['get_payment_intent'],
          created_at: base_time - 1.day
        )
        AiRequestAudit.create!(
          request_id: 'demo_req_002', endpoint: '/api/v1/ai/chat', merchant_id: m.id,
          agent_key: 'payment_support', success: true, tool_used: true, tool_names: ['get_ledger_summary'],
          created_at: base_time - 2.hours
        )

        # Store for summary (use global IDs so demo script can reference them)
        @summary = {
          demo_merchant_id: m.id,
          demo_email: DEMO_EMAIL,
          demo_password: DEMO_PASSWORD,
          demo_api_key: @api_keys[DEMO_EMAIL],
          scoping_email: SCOPING_EMAIL,
          scoping_password: SCOPING_PASSWORD,
          payment_intent_created: pi_created.id,
          payment_intent_authorized: pi_auth.id,
          payment_intent_captured: pi_captured.id,
          payment_intent_refunded: pi_refunded.id,
          payment_intent_failed: pi_failed.id,
          payment_intent_canceled: pi_canceled.id,
          transaction_capture: t_cap_b.id,
          transaction_refund: t_ref.id,
          webhook_succeeded: we_succ.id,
          webhook_failed: we_fail.id,
          webhook_pending: we_pend.id
        }
      end

      def seed_scoping_merchant_data
        m = @scoping_merchant
        base = Time.current - 2.days

        c = Customer.create!(merchant: m, email: 'other@scoping.example.com', name: 'Other User')
        pm = PaymentMethod.create!(customer: c, method_type: 'card', last4: '0000', brand: 'Visa', exp_month: 1, exp_year: 2026)

        pi = PaymentIntent.create!(
          merchant: m, customer: c, payment_method: pm,
          amount_cents: 1000, currency: 'USD', status: 'captured',
          idempotency_key: 'scoping_001',
          created_at: base, updated_at: base
        )
        Transaction.create!(payment_intent: pi, kind: 'authorize', status: 'succeeded', amount_cents: 1000, processor_ref: 'sc_txn_a', created_at: base, updated_at: base)
        t = Transaction.create!(payment_intent: pi, kind: 'capture', status: 'succeeded', amount_cents: 1000, processor_ref: 'sc_txn_c', created_at: base, updated_at: base)
        LedgerEntry.create!(merchant: m, payment_transaction: t, entry_type: 'charge', amount_cents: 1000, currency: 'USD', created_at: base, updated_at: base)

        WebhookEvent.create!(
          merchant: m, event_type: 'payment_intent.captured',
          payload: { payment_intent_id: pi.id }, delivery_status: 'succeeded',
          delivered_at: base + 1.minute, attempts: 1, created_at: base, updated_at: base
        )
      end

      def build_summary
        # Keep @summary from seed_demo_merchant_data; add human-readable IDs if needed
        true
      end
    end
  end
end
